try :
    print(x, end=" - ")
finally:
    print("An exception occurred")